# Generated by Django 2.0.3 on 2019-09-12 07:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(upload_to='blog/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='blog/')),
                ('image3', models.FileField(blank=True, null=True, upload_to='blog/')),
                ('image4', models.FileField(blank=True, null=True, upload_to='blog/')),
                ('image5', models.FileField(blank=True, null=True, upload_to='blog/')),
                ('title', models.CharField(max_length=200)),
                ('discription', ckeditor.fields.RichTextField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('Status', models.BooleanField(default=False)),
                ('view', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
