# Generated by Django 2.0.3 on 2019-09-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_company_footer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_footer_link',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
