# Generated by Django 2.0.3 on 2019-09-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_company_footer_link_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_footer_link',
            name='google_plas',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='company_footer_link',
            name='tweeter',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='company_footer_link',
            name='youtube',
            field=models.TextField(blank=True, max_length=254),
        ),
    ]
