# Generated by Django 2.0.3 on 2019-09-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20190913_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_meta_title', models.TextField(blank=True)),
                ('index_meta_description', models.TextField(blank=True)),
                ('index_meta_keywords', models.TextField(blank=True)),
                ('blog_title', models.TextField(blank=True)),
                ('blog_description', models.TextField(blank=True)),
                ('blog_keywords', models.TextField(blank=True)),
                ('contact_title', models.TextField(blank=True)),
                ('contact_description', models.TextField(blank=True)),
                ('contact_keywords', models.TextField(blank=True)),
                ('base_title', models.TextField(blank=True)),
                ('base_description', models.TextField(blank=True)),
                ('base_keywords', models.TextField(blank=True)),
                ('blog_detail_title', models.TextField(blank=True)),
                ('base_detail_description', models.TextField(blank=True)),
                ('base_detail_keywords', models.TextField(blank=True)),
                ('properties_title', models.TextField(blank=True)),
                ('properties_description', models.TextField(blank=True)),
                ('properties_keywords', models.TextField(blank=True)),
                ('about_us_title', models.TextField(blank=True)),
                ('about_us_description', models.TextField(blank=True)),
                ('about_us_keywords', models.TextField(blank=True)),
                ('properties_detail_title', models.TextField(blank=True)),
                ('properties_detail_description', models.TextField(blank=True)),
                ('properties_detail_keywords', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'SeoContent',
                'verbose_name_plural': 'SeoContents',
            },
        ),
    ]
