# Generated by Django 2.0.3 on 2019-09-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_seocontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='seocontent',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
