# Generated by Django 2.0.3 on 2019-09-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_seocontent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='seo_discription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_keyword',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='properte',
            name='seo_discription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='properte',
            name='seo_keyword',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='properte',
            name='seo_title',
            field=models.TextField(blank=True),
        ),
    ]
