# Generated by Django 2.0.3 on 2019-09-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_auto_20190916_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='mail',
            field=models.CharField(default=-12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.CharField(default=-12, max_length=50),
            preserve_default=False,
        ),
    ]
