# Generated by Django 2.0.3 on 2019-09-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20190917_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='mail',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
