# Generated by Django 2.0.3 on 2019-09-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20190917_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properte',
            name='image1',
            field=models.ImageField(upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='properte',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='properte',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='properte',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='properte',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='property/'),
        ),
    ]
