# Generated by Django 2.0.3 on 2019-09-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20190920_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properte',
            name='image2',
            field=models.ImageField(blank=True, height_field='200px', null=True, upload_to='property/', width_field='200px'),
        ),
    ]
