# Generated by Django 2.0.3 on 2019-09-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_auto_20190920_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properte',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='property/'),
        ),
    ]
