# Generated by Django 2.0.3 on 2019-09-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_auto_20190920_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properte',
            name='image2',
        ),
    ]
