# Generated by Django 2.0.3 on 2019-09-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_properte_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properte',
            old_name='Suggeste',
            new_name='feature_property',
        ),
    ]
